language: c
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - opam
      - aspcud
env:
  matrix:
    - MODE=build COQ_VERSION=8.7.0
    - MODE=matcher COQ_VERSION=8.7.0
script: bash -ex .travis-ci.sh
sudo: false
notifications:
  email: false
